# Generated by Django 5.1.5 on 2026-03-16 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MpesaAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MpesaTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        help_text="M-Pesa transaction ID", max_length=50, unique=True
                    ),
                ),
                (
                    "merchant_request_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "checkout_request_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("stk_push", "STK Push"),
                            ("c2b", "Customer to Business"),
                            ("b2c", "Business to Customer"),
                        ],
                        default="stk_push",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Phone number in format 254XXXXXXXXX", max_length=15
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Internal reference (e.g., property_id, invoice_id)",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "response_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("response_description", models.TextField(blank=True, null=True)),
                ("raw_response", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mpesa_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction_id"], name="mpesa_mpesa_transac_bfb356_idx"
                    ),
                    models.Index(
                        fields=["checkout_request_id"],
                        name="mpesa_mpesa_checkou_ad0fa5_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="mpesa_mpesa_user_id_fbd830_idx"
                    ),
                ],
            },
        ),
    ]
