# Generated by Django 5.1.5 on 2026-03-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Kenyan mobile number (e.g. 0712345678)",
                max_length=15,
                null=True,
            ),
        ),
    ]
