# Generated by Django 4.2 on 2025-12-22 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("bedsitter", "Bedsitter"),
                            ("single_room", "Single room"),
                            ("one_bedroom", "1-bedroom"),
                            ("hostel", "Hostel"),
                            ("shared", "Shared"),
                        ],
                        default="bedsitter",
                        max_length=32,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Address or description of where the property is located (e.g. Machakos Town).",
                        max_length=255,
                    ),
                ),
                (
                    "nearby_shopping_center",
                    models.CharField(
                        blank=True,
                        help_text="Nearest shopping center or landmark.",
                        max_length=255,
                    ),
                ),
                (
                    "monthly_rent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly rent in Kenyan Shillings (KES).",
                        max_digits=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "landlord",
                    models.ForeignKey(
                        help_text="The landlord (owner) who listed this property.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property_images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                    ),
                ),
            ],
        ),
    ]
