# Generated by Django 5.1.5 on 2025-12-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="neighborhood",
            field=models.CharField(
                choices=[
                    ("machakos_cbd", "Machakos CBD"),
                    ("mikuyuni", "Mikuyuni"),
                    ("matungulu", "Matungulu"),
                    ("kangundo", "Kangundo"),
                    ("kiambu", "Kiambu"),
                    ("other", "Other"),
                ],
                default="machakos_cbd",
                help_text="Neighborhood or area in Machakos.",
                max_length=32,
            ),
        ),
    ]
