# Generated by Django 4.2 on 2026-01-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_add_savedproperty_table"),
        ("properties", "0004_propertyinquiry"),
    ]

    operations = []
