# Generated by Django 4.2 on 2026-01-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_update_propertyinquiry_fields"),
        ("properties", "0005_merge_20260107_1108"),
    ]

    operations = []
