# Generated by Django 5.1.5 on 2026-02-12 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_fix_propertyinquiry_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload a short video of the property (optional).",
                null=True,
                upload_to="property_videos/",
            ),
        ),
        migrations.AlterField(
            model_name="savedproperty",
            name="property",
            field=models.ForeignKey(
                help_text="Property that was saved.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by",
                to="properties.property",
            ),
        ),
        migrations.AlterField(
            model_name="savedproperty",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant who saved this property.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
