# Generated by Django 5.1.5 on 2026-02-12 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_add_property_video"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(help_text="Message content.")),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as read for future notification features.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        help_text="The inquiry this message belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="properties.propertyinquiry",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="User who sent this message (tenant or landlord).",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
