# Generated by Django 5.1.5 on 2026-02-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0011_populate_message_receiver"),
    ]

    operations = []
