# Generated by Django 5.1.5 on 2026-03-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0012_make_receiver_non_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="featured_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
