# Generated by Cursor on 2026-03-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0013_alter_message_receiver"),
        ("properties", "0014_payment_tenantallocation_rentpayment"),
    ]

    operations = []

