# Generated by Cursor on 2026-03-16

from django.db import migrations


def backfill_allocation_landlord_and_rent(apps, schema_editor):
    TenantAllocation = apps.get_model("properties", "TenantAllocation")
    for alloc in TenantAllocation.objects.select_related("property").all():
        updates = {}
        prop = getattr(alloc, "property", None)
        if prop is None:
            continue
        if alloc.landlord_id is None:
            updates["landlord_id"] = prop.landlord_id
        # property model uses monthly_rent
        if getattr(alloc, "rent_amount", None) != prop.monthly_rent:
            updates["rent_amount"] = prop.monthly_rent
        if updates:
            TenantAllocation.objects.filter(pk=alloc.pk).update(**updates)


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0016_contactpayment_featuredpayment_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_allocation_landlord_and_rent, migrations.RunPython.noop),
    ]

