# Generated by Cursor on 2026-03-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0017_backfill_allocation_landlord_and_rent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantallocation",
            name="landlord",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_allocations_as_landlord",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

