# Generated by Django 4.2.28 on 2026-03-19 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_alter_tenantallocation_landlord_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantallocation',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tenantallocation',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
